name: kh_hw1env
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - anyio=3.5.0=py37haa95532_0
  - argcomplete=1.12.3=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py37h2bbff1b_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotli=1.0.9=h8ffe710_6
  - brotli-bin=1.0.9=h8ffe710_6
  - brotlipy=0.7.0=py37h2bbff1b_1003
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=py37_0
  - cffi=1.15.0=py37h2bbff1b_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cryptography=36.0.0=py37h21b164f_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.11.0=py37he774522_0
  - dask-core=1.1.4=py37_1
  - debugpy=1.5.1=py37hd77b12b_0
  - decorator=4.4.2=py_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py37_0
  - et_xmlfile=1.0.1=py_1001
  - fonttools=4.29.1=py37hcc03f2d_0
  - freeglut=3.2.2=h0e60522_1
  - freetype=2.10.4=h546665d_1
  - icu=68.2=h0e60522_0
  - idna=3.3=pyhd3eb1b0_0
  - imageio=2.9.0=py_0
  - importlib-metadata=4.8.2=py37haa95532_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - intel-openmp=2022.0.0=h57928b3_3663
  - ipykernel=6.4.1=py37haa95532_1
  - ipython=7.31.1=py37haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jasper=2.0.33=h77af90b_0
  - jbig=2.1=h8d14728_2003
  - jdcal=1.4.1=py_0
  - jedi=0.18.1=py37haa95532_1
  - jinja2=3.0.2=pyhd3eb1b0_0
  - jpeg=9e=h8ffe710_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter_client=7.1.2=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py37haa95532_0
  - jupyter_server=1.13.5=pyhd3eb1b0_0
  - jupyterlab=3.2.9=pyhd3eb1b0_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.10.3=pyhd3eb1b0_1
  - kiwisolver=1.2.0=py37h74a9793_0
  - lerc=3.0=h0e60522_0
  - libblas=3.9.0=13_win64_mkl
  - libbrotlicommon=1.0.9=h8ffe710_6
  - libbrotlidec=1.0.9=h8ffe710_6
  - libbrotlienc=1.0.9=h8ffe710_6
  - libcblas=3.9.0=13_win64_mkl
  - libclang=11.1.0=default_h5c34c98_1
  - libdeflate=1.10=h8ffe710_0
  - liblapack=3.9.0=13_win64_mkl
  - liblapacke=3.9.0=13_win64_mkl
  - libopencv=4.5.5=py37h04cf790_2
  - libpng=1.6.37=h1d00b33_2
  - libprotobuf=3.19.4=h7755175_0
  - libtiff=4.3.0=hc4061b1_3
  - libwebp-base=1.2.2=h8ffe710_1
  - libzlib=1.2.11=h8ffe710_1013
  - lz4-c=1.9.3=h8ffe710_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.0.1=py37h2bbff1b_0
  - matplotlib=3.5.1=py37h03978a9_0
  - matplotlib-base=3.5.1=py37h4a79c79_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py37hfa6e2cd_1001
  - mkl=2022.0.0=h0e2418a_796
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclassic=0.3.5=pyhd3eb1b0_0
  - nbclient=0.5.11=pyhd3eb1b0_0
  - nbconvert=6.1.0=py37haa95532_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - networkx=2.5=py_0
  - notebook=6.4.8=py37haa95532_0
  - numpy=1.21.5=py37h5fa1a60_0
  - olefile=0.46=py37_0
  - opencv=4.5.5=py37h03978a9_2
  - openpyxl=3.0.5=py_0
  - openssl=1.1.1m=h2bbff1b_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.3.4=py37h9386db6_1
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.0.0=py37hca74424_0
  - pip=21.2.4=py37haa95532_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - py-opencv=4.5.5=py37h4038f58_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.12.3=py37h03978a9_8
  - pyqt-impl=5.12.3=py37hf2a7229_8
  - pyqt5-sip=4.19.18=py37hf2a7229_8
  - pyqtchart=5.12=py37hf2a7229_8
  - pyqtwebengine=5.12.1=py37hf2a7229_8
  - pyrsistent=0.18.0=py37h196d8e1_0
  - pysocks=1.7.1=py37_1
  - python=3.7.11=h6244533_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=2_cp37m
  - pytz=2021.3=pyhd8ed1ab_0
  - pywavelets=1.1.1=py37he774522_2
  - pywin32=302=py37h827c3e9_1
  - pywinpty=2.0.2=py37h5da7b33_0
  - pyzmq=22.3.0=py37hd77b12b_2
  - qt=5.12.9=h5909a2a_4
  - requests=2.27.1=pyhd3eb1b0_0
  - scikit-image=0.17.2=py37h1e1f486_0
  - scipy=1.7.3=py37hb6553fb_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py37haa95532_0
  - six=1.15.0=py_0
  - sniffio=1.2.0=py37haa95532_1
  - sqlite=3.37.2=h2bbff1b_0
  - tbb=2021.5.0=h2d74725_0
  - terminado=0.13.1=py37haa95532_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tifffile=2020.10.1=py37h8c2d366_2
  - tk=8.6.10=he774522_0
  - toolz=0.11.1=py_0
  - tornado=6.1=py37h2bbff1b_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - unicodedata2=14.0.0=py37hcc03f2d_0
  - urllib3=1.26.8=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py37_1
  - websocket-client=0.58.0=py37haa95532_4
  - wheel=0.37.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py37haa95532_0
  - wincertstore=0.2=py37haa95532_2
  - winpty=0.4.3=4
  - xlsxwriter=1.3.7=py_0
  - xz=5.2.5=h62dcd97_1
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h8ffe710_1013
  - zstd=1.5.2=h6255e5f_0
prefix: C:\Users\12029\anaconda3\envs\computervision
